---
- name: Create bot run user
  become: true
  user:
    name: bot
    comment: The bot runner user
    create_home: true

- name: Create application directory
  become: true
  file:
    path: /home/bot/kkkj
    state: directory
    owner: bot
    group: bot
    mode: '0770'