---
- name: Install aws cli
  become: true
  apt:
    name: awscli
    update_cache: true

- name: Install jq
  become: true
  apt:
    name: jq

- name: Send get_env.sh
  become: true
  copy:
    src: ./roles/prepare/files/get_env.sh
    dest: /usr/bin/get_env.sh
    owner: root
    group: root
    mode: '0775'
  
- name: Send download_release.sh
  become: true
  copy:
    src: ./roles/prepare/files/download_release.sh
    dest: /usr/bin/download_release.sh
    owner: root
    group: root
    mode: '0775'

- name: Send systemctl unit file
  become: true
  copy:
    src: ./roles/prepare/files/kkkjbot.service
    dest: /etc/systemd/system/kkkjbot.service
    owner: root
    group: root
    mode: '0774'

- name: Reload systemd units
  become: true
  command: systemctl daemon-reload

- name: Enable systemd kkkjbot.service
  become: true
  command: systemctl enable kkkjbot.service